### ISSUE TITLE
Increase your attempting speed

### ISSUE THREAD

**Issue by ghost** [ARISHA-MUGHAL/Typescript-assignments#1]
Please attempt your assignment as fast as possible.

**Comment by ARISHA-MUGHAL** [comment]
Sure, now my main focus is learning, so I am using my time to learn
JavaScript so I can complete my work with my own effort. Otherwise, I could
simply copy and paste all 45 assignments.
Btw who are you ?

**Comment by ghost** [comment]
I am Saad Farhan. Teacher Assistant from Saturday 7pm to 10pm. The
submissions have started being checked. So when I found yours, you haven't
done all exercises. I meant that you are free to do Google search on how to
do the particle thing in TypeScript/JavaScript. You can start doing from
the corresponding exercise one by one and it will end easily.

**Comment by ARISHA-MUGHAL** [comment]
Oki Teacher assistant I am trying to do as soon as possible . I'll complete
all exercise by this Saturday In Sha Allah.

**Comment by ghost** [comment]
JazakAllah khairan 😊. Close this issue after completing the assignment.
